In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Ram","Sham","Seeta","Geeta","Riya"],
    "CGPA" : [3.5 ,1.2 ,10, 0.9, 9]
}

# Series 

> One - Dimentional Label Array
>
> ```Label```= Named Index <br>
> ```Index```= Position

In [3]:
data = pd.Series(info)

print(data)
data["Name"][0]

Name    [Ram, Sham, Seeta, Geeta, Riya]
CGPA             [3.5, 1.2, 10, 0.9, 9]
dtype: object

'Ram'

In [4]:
data.index

Index(['Name', 'CGPA'], dtype='str')

In [5]:
df = pd.Series([23,12,34,65,75], index=["Ram","Sham","Geeta","Seeta","Rohit"])

In [6]:
df

Ram      23
Sham     12
Geeta    34
Seeta    65
Rohit    75
dtype: int64

## Indexing

In [7]:
print(df["Ram"])
df.index

23

Index(['Ram', 'Sham', 'Geeta', 'Seeta', 'Rohit'], dtype='str')

# Characteristics

- Homogenious (Same Data Type)
- Vectorized Operation (No Need Of Loop For Operation Like Add etc)
- Handling Missing Value with **NaN**
- Mutable Values , But Size Immutable

# Data Frame

In [8]:
data = pd.DataFrame(info , index=range(1,6) )

In [9]:
data

    Name  CGPA
1    Ram   3.5
2   Sham   1.2
3  Seeta  10.0
4  Geeta   0.9
5   Riya   9.0

In [10]:
print(data, type(data))

    Name  CGPA
1    Ram   3.5
2   Sham   1.2
3  Seeta  10.0
4  Geeta   0.9
5   Riya   9.0 <class 'pandas.DataFrame'>

In [11]:
data.index

RangeIndex(start=1, stop=6, step=1)

In [12]:
data.columns

Index(['Name', 'CGPA'], dtype='str')

## Creating Data Frame By List Of List

In [13]:
data = pd.DataFrame([["Ram",12],["Sham",54],["Geeta",65]], columns=["Name","Age"], index=range(1,4))

In [14]:
data

    Name  Age
1    Ram   12
2   Sham   54
3  Geeta   65

In [15]:
import numpy as np

In [16]:
np_arr = np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(np_arr, columns=["A","B","C"])

In [17]:
df

   A  B  C
0  1  2  3
1  4  5  6

# Working With CSV And Json Files

In [18]:
data = pd.read_csv("employee_data.csv")

In [19]:
data

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [20]:
data.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [21]:
data.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [22]:
data.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [23]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

In [26]:
data.sample()

   ID Name  Age Department  Salary
8   9  Ian   35         IT   75000

In [25]:
data.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')