# 📊 Normalizing and Scaling Data

Feature scaling is a **data preprocessing technique** used to bring numerical features to a comparable scale.

Different features can have very different ranges.

For example:

| Feature | Range |
|---|---:|
| Age | 18–60 |
| Salary | ₹20,000–₹2,00,000 |
| Experience | 0–30 years |

If an ML algorithm uses distances, gradients, or feature magnitudes, a feature with very large values can dominate the others.

### Main Scaling Techniques

1. **Standard Scaling**
2. **Min-Max Scaling**
3. **Robust Scaling**

> **Important:** Scaling changes the numerical representation of data, but it does not change the underlying information.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Why Do We Need Feature Scaling?

Consider two features:

- `Age` → values between 18 and 60
- `Salary` → values between 20,000 and 200,000

Their numerical ranges are very different.

For a distance-based algorithm, the salary feature can dominate the distance simply because its numbers are much larger.

For example:

$$ \text{Distance} = \sqrt{(\text{Age}_1 - \text{Age}_2)^2 + (\text{Salary}_1 - \text{Salary}_2)^2} $$

The salary difference can become much larger than the age difference.

Scaling transforms these features into comparable numerical ranges.

### Scaling is especially important for:

- K-Nearest Neighbors (KNN)
- K-Means Clustering
- Support Vector Machines (SVM)
- Principal Component Analysis (PCA)
- Logistic Regression
- Neural Networks
- Regularized Linear Models

# 2. Example Dataset

Let's create a simple dataset containing:

- Age
- Salary
- Experience

Notice that each feature has a different range.

In [2]:
data = pd.DataFrame({
    "Age": [18, 20, 25, 30, 40],
    "Salary": [20000, 30000, 50000, 80000, 150000],
    "Experience": [0, 1, 3, 7, 15]
})

data

   Age  Salary  Experience
0   18   20000           0
1   20   30000           1
2   25   50000           3
3   30   80000           7
4   40  150000          15

In [3]:
data.describe()

             Age        Salary  Experience
count   5.000000       5.00000     5.00000
mean   26.600000   66000.00000     5.20000
std     8.820431   52249.40191     6.09918
min    18.000000   20000.00000     0.00000
25%    20.000000   30000.00000     1.00000
50%    25.000000   50000.00000     3.00000
75%    30.000000   80000.00000     7.00000
max    40.000000  150000.00000    15.00000

# 3. Standard Scaling

Standard Scaling transforms a feature so that it approximately has:

- Mean = **0**
- Standard deviation = **1**

The formula is:
$$
z = \frac{x-\mu}{\sigma}
$$

Where:

- $x$ = original value
- $\mu$ = mean of the feature
- $\sigma$ = standard deviation
- $z$ = scaled value

### Example

Suppose:
$$ \mu = 50 $$ 
$$ \sigma = 10 $$ 
and: 
$$ x = 70 $$ 
Then: 
$$ z = \frac{70-50}{10}=2 $$

So `70` becomes `2`.

This means the value is **2 standard deviations above the mean**.

### Scikit-Learn

```python
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

In [4]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

data_standard = standard_scaler.fit_transform(data)

data_standard_df = pd.DataFrame(
    data_standard,
    columns=data.columns
)

data_standard_df

        Age    Salary  Experience
0 -1.090093 -0.984309   -0.953206
1 -0.836583 -0.770329   -0.769897
2 -0.202808 -0.342368   -0.403280
3  0.430967  0.299572    0.329956
4  1.698517  1.797434    1.796427

# 4. Understanding `fit()` and `transform()`

Two important operations are used during preprocessing.

### `fit()`

The scaler learns information from the data.

For `StandardScaler`, it learns:

- Mean
- Standard deviation

### `transform()`

The scaler uses the learned information to transform the data.

Therefore:

```text
fit()
  ↓
Learn parameters
  ↓
transform()
  ↓
Transform data

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit_transform(data)

array([[-1.09009327, -0.98430913, -0.95320625],
       [-0.83658321, -0.77032889, -0.76989735],
       [-0.20280805, -0.34236839, -0.40327957],
       [ 0.43096711,  0.29957234,  0.32995601],
       [ 1.69851742,  1.79743407,  1.79642716]])

In [8]:
scaler.fit(data)
data_scaled = scaler.transform(data)
data_scaled

array([[-1.09009327, -0.98430913, -0.95320625],
       [-0.83658321, -0.77032889, -0.76989735],
       [-0.20280805, -0.34236839, -0.40327957],
       [ 0.43096711,  0.29957234,  0.32995601],
       [ 1.69851742,  1.79743407,  1.79642716]])

# 5. Min-Max Scaling

Min-Max Scaling transforms values into a fixed range.

The most common range is:
$$ [0,1] $$

The formula is:

$$
x' = \frac{x-x_{min}}{x_{max}-x_{min}}
$$

Where:

- $x$ = original value
- $x_{min}$ = minimum value
- $x_{max}$ = maximum value
- $x'$ = scaled value

### Example

Suppose:

- Minimum = 10
- Maximum = 50
- Value = 30

Then:

$$
x' = \frac{30-10}{50-10}
$$

$$
x' = \frac{20}{40}=0.5
$$

Therefore:

```text
30 → 0.5

In [9]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

In [13]:
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()

data_minmax = minmax_scaler.fit_transform(data)

# By default scaler return array so we need to convert it to data frame
data_minmax_df = pd.DataFrame(
    data_minmax,
    columns=data.columns
)

data_minmax_df

        Age    Salary  Experience
0  0.000000  0.000000    0.000000
1  0.090909  0.076923    0.066667
2  0.318182  0.230769    0.200000
3  0.545455  0.461538    0.466667
4  1.000000  1.000000    1.000000

# 6. Robust Scaling

Robust Scaling is useful when the dataset contains **outliers**.

Instead of using:

- Mean
- Standard deviation

Robust Scaling uses:

- Median
- Interquartile Range (IQR)

The formula is:
$$
x' = \frac{x-\text{Median}}{IQR}
$$

Where:

$$
IQR = Q_3-Q_1
$$


### Why is this useful?

Mean and standard deviation can be strongly affected by extreme values.

Median and IQR are much more resistant to outliers.

Therefore:

```text
StandardScaler
    ↓
Mean + Standard Deviation
    ↓
More affected by outliers


RobustScaler
    ↓
Median + IQR
    ↓
More resistant to outliers

In [14]:
from sklearn.preprocessing import RobustScaler

robust_scaler = RobustScaler()

data_robust = robust_scaler.fit_transform(data)

data_robust_df = pd.DataFrame(
    data_robust,
    columns=data.columns
)

data_robust_df

   Age  Salary  Experience
0 -0.7    -0.6   -0.500000
1 -0.5    -0.4   -0.333333
2  0.0     0.0    0.000000
3  0.5     0.6    0.666667
4  1.5     2.0    2.000000

# 7. What is IQR?

IQR stands for **Interquartile Range**.

It represents the range of the middle 50% of the data.

$$
IQR = Q_3-Q_1
$$

Where:

- $Q_1$ = 25th percentile
- $Q_3$ = 75th percentile


Conceptually:

```text
Minimum
   │
   ▼
   ├──── Q1 ──── Median ──── Q3 ────┤
   │                                  │
   └──────────── IQR ────────────────┘

# 8. Comparing the Three Scalers

| Scaler | Main Statistics | Typical Range | Outlier Sensitivity |
|---|---|---|---|
| StandardScaler | Mean + Standard Deviation | Not fixed | High |
| MinMaxScaler | Minimum + Maximum | Usually 0–1 | Very High |
| RobustScaler | Median + IQR | Not fixed | Low |

### Quick Memory Trick 🧠

> **StandardScaler → Mean + Standard Deviation**

> **MinMaxScaler → Minimum + Maximum**

> **RobustScaler → Median + IQR**

In [15]:
scalers = {
    "StandardScaler": StandardScaler(),
    "MinMaxScaler": MinMaxScaler(),
    "RobustScaler": RobustScaler()
}

scaled_results = {}

for name, scaler in scalers.items():
    scaled_data = scaler.fit_transform(data)
    
    scaled_results[name] = pd.DataFrame(
        scaled_data,
        columns=data.columns
    )

scaled_results

{'StandardScaler':         Age    Salary  Experience
 0 -1.090093 -0.984309   -0.953206
 1 -0.836583 -0.770329   -0.769897
 2 -0.202808 -0.342368   -0.403280
 3  0.430967  0.299572    0.329956
 4  1.698517  1.797434    1.796427,
 'MinMaxScaler':         Age    Salary  Experience
 0  0.000000  0.000000    0.000000
 1  0.090909  0.076923    0.066667
 2  0.318182  0.230769    0.200000
 3  0.545455  0.461538    0.466667
 4  1.000000  1.000000    1.000000,
 'RobustScaler':    Age  Salary  Experience
 0 -0.7    -0.6   -0.500000
 1 -0.5    -0.4   -0.333333
 2  0.0     0.0    0.000000
 3  0.5     0.6    0.666667
 4  1.5     2.0    2.000000}

# 9. Understanding Outliers

### 📊 The Problem Dataset
Consider this dataset containing an extreme anomaly:
```text
10, 12, 13, 15, 16, 18, 1000
```
Here, **1000** is an extreme outlier that severely distorts traditional scaling methods.

---

### 🔍 Impact on Scaling Techniques

#### 1. Min-Max Scaling (Sensitive)
$$ x' = \frac{x - x_{min}}{x_{max} - x_{min}} $$
* **The Issue:** Because $1000$ becomes $x_{max}$, the denominator becomes very large ($1000 - 10 = 990$). 
* **The Result:** Normal data points (like $12$ or $15$) get heavily compressed and clustered extremely close to $0$.

#### 2. Standard Scaling / Z-Score (Sensitive)
$$ z = \frac{x - \mu}{\sigma} $$
* **The Issue:** The extreme value heavily pulls the mean ($\mu$) upward and drastically inflates the standard deviation ($\sigma$).
* **The Result:** Normal data points lose their relative variance because the scaling parameters are skewed by a single anomaly.

#### 3. Robust Scaling (Resilient)
$$ x' = \frac{x - \text{Median}}{IQR} $$
* **The Issue:** None. It swaps the mean and range for the **Median** and **Interquartile Range (IQR)**.
* **The Result:** Because percentiles ignore extreme tail values, the core data scales perfectly, making this method highly resilient to outliers.

---

### Summary Comparison Table

| Scaling Method | Core Metrics Used | Outlier Sensitivity | Best Used For... |
| :--- | :--- | :--- | :--- |
| **Min-Max** | Min / Max | 🔴 **High** | Uniform distributions, bounded boundaries (e.g., Image Pixels $[0,1]$). |
| **Standard** | Mean / Std Dev | 🔴 **High** | Normally distributed data (Gaussian), algorithms expecting zero-mean. |
| **Robust** | Median / IQR | 🟢 **Low** | Datasets with heavy outliers, skewed features. |

In [16]:
outlier_data = pd.DataFrame({
    "Value": [10, 12, 13, 15, 16, 18, 1000]
})

outlier_data

   Value
0     10
1     12
2     13
3     15
4     16
5     18
6   1000

In [17]:
standard_outlier = StandardScaler().fit_transform(
    outlier_data
)

minmax_outlier = MinMaxScaler().fit_transform(
    outlier_data
)

robust_outlier = RobustScaler().fit_transform(
    outlier_data
)

comparison = pd.DataFrame({
    "Original": outlier_data["Value"],
    "StandardScaler": standard_outlier.flatten(),
    "MinMaxScaler": minmax_outlier.flatten(),
    "RobustScaler": robust_outlier.flatten()
})

comparison

   Original  StandardScaler  MinMaxScaler  RobustScaler
0        10       -0.419831      0.000000     -1.111111
1        12       -0.414034      0.002020     -0.666667
2        13       -0.411136      0.003030     -0.444444
3        15       -0.405340      0.005051      0.000000
4        16       -0.402442      0.006061      0.222222
5        18       -0.396645      0.008081      0.666667
6      1000        2.449428      1.000000    218.888889

# 10. Important Train-Test Scaling Rule ⚠️

When building a machine learning model, we usually divide the dataset into:

- **Training data** → used to learn the model
- **Test data** → used to evaluate the model

The scaler must be fitted **only on the training data**.

---


```
Original Dataset
       │
       ▼
Train-Test Split
       │
       ├───────────────┐
       ▼               ▼
   Training          Testing
       │               │
       ▼               │
    scaler.fit()       │
       │               │
       ▼               │
 scaler.transform()    │
       │               │
       ▼               ▼
Scaled Training    scaler.transform()
                       │
                       ▼
                  Scaled Testing

```

# 13. Which Scaler Should You Choose? 🤔

There is no single scaler that is always the best.

The appropriate scaler depends on the **distribution of your data**, the presence of **outliers**, and the requirements of your ML algorithm.

---

## 🟦 StandardScaler

### How it works

Standardizes features using:

- Mean
- Standard deviation

\[
z = \frac{x-\mu}{\sigma}
\]

### Use it when:

- You want features centered around `0`.
- You want a standard deviation close to `1`.
- Your data does not contain severe outliers.
- Your algorithm is sensitive to feature magnitude.

### Commonly useful for:

- Logistic Regression
- Linear Models
- SVM
- PCA
- Neural Networks

---

## 🟩 MinMaxScaler

### How it works

Maps features to a fixed range, usually `[0, 1]`.

\[
x' = \frac{x-x_{\min}}{x_{\max}-x_{\min}}
\]

### Use it when:

- You specifically need a bounded range.
- A fixed range such as `[0, 1]` is useful.
- Your data does not contain problematic outliers.

### Commonly useful for:

- Neural Networks
- Distance-based algorithms
- Some image-related numerical features

### ⚠️ Important

Min-Max Scaling is highly sensitive to outliers because it uses the minimum and maximum values.

---

## 🟨 RobustScaler

### How it works

Uses:

- Median
- Interquartile Range (IQR)

\[
x' = \frac{x-\text{Median}}{IQR}
\]

### Use it when:

- Your dataset contains significant outliers.
- Extreme values should have less influence on scaling.
- Median and IQR provide a better representation of the data.

### Main advantage

It is generally more resistant to outliers than StandardScaler and MinMaxScaler.

---

## Quick Decision Guide

```text
              Do you have significant outliers?
                         │
              ┌──────────┴──────────┐
             YES                    NO
              │                      │
              ▼                      ▼
        RobustScaler       Do you need a fixed
                           range such as [0,1]?
                                  │
                         ┌────────┴────────┐
                        YES                NO
                         │                  │
                         ▼                  ▼
                   MinMaxScaler       StandardScaler

# 14. Which Machine Learning Algorithms Need Scaling?

Scaling is particularly important for algorithms whose calculations depend on **distance, magnitude, gradients, or geometric relationships**.

| Algorithm | Scaling Usually Needed? | Why? |
|---|---|---|
| K-Nearest Neighbors (KNN) | ✅ Yes | Distance-based |
| K-Means | ✅ Yes | Distance-based |
| SVM | ✅ Yes | Distance / margin-based |
| PCA | ✅ Yes | Variance and feature magnitude |
| Logistic Regression | ✅ Usually | Optimization / regularization |
| Neural Networks | ✅ Usually | Gradient-based optimization |
| Linear Regression | ⚠️ Often useful | Optimization / regularization |
| Decision Tree | ❌ Usually not | Rule-based splits |
| Random Forest | ❌ Usually not | Tree-based |
| XGBoost | ❌ Usually not | Tree-based |

---

# 15. 🧠 Final Scaling Cheat Sheet

## StandardScaler

### Formula

$$
z = \frac{x-\mu}{\sigma}
$$

### Uses

**Mean + Standard Deviation**

### Result

- Mean ≈ `0`
- Standard deviation ≈ `1`
- No fixed minimum or maximum

### Best suited for

General-purpose scaling when extreme outliers are not a major concern.

---

## MinMaxScaler

### Formula

$$
x' = \frac{x-x_{\min}}{x_{\max}-x_{\min}}
$$

### Uses

**Minimum + Maximum**

### Result

Usually:

$$
0 \leq x' \leq 1
$$

### Best suited for

Situations where a fixed range is desirable and outliers are not problematic.

---

## RobustScaler

### Formula

$$
x' = \frac{x-\text{Median}}{IQR}
$$

where:

$$
IQR = Q_3-Q_1
$$

### Uses

**Median + IQR**

### Result

A representation that is less influenced by extreme values.

### Best suited for

Datasets containing significant outliers.

---

# 🔥 The 3-Second Memory Rule

```text
StandardScaler
      ↓
Mean + Standard Deviation


MinMaxScaler
      ↓
Minimum + Maximum


RobustScaler
      ↓
Median + IQR

```
             Raw Dataset
                  │
                  ▼
            Train-Test Split
                  │
          ┌───────┴───────┐
          ▼               ▼
       Training          Testing
          │               │
          ▼               │
     scaler.fit()         │
          │               │
          ▼               │
 scaler.transform()       │
          │               │
          ▼               ▼
   Scaled Training   scaler.transform()
                            │
                            ▼
                     Scaled Testing
                            │
                            ▼
                       Train Model
                            │
                            ▼
                         Evaluate


```